package node

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestDetectPackageJSON(t *testing.T) {
	d := &detector{}
	dir := t.TempDir()

	ok, err := d.Detect(dir)
	if err != nil {
		t.Fatalf("Detect (no package.json): %v", err)
	}
	if ok {
		t.Error("Detect should be false when package.json is absent")
	}

	if err := os.WriteFile(filepath.Join(dir, "package.json"), []byte("{}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	ok, err = d.Detect(dir)
	if err != nil {
		t.Fatalf("Detect (with package.json): %v", err)
	}
	if !ok {
		t.Error("Detect should be true when package.json is present")
	}
}

// Lockfile fixtures. What distinguishes the two is the `__metadata:` block
// Berry writes near the top; Classic's header is a pair of comments.
const (
	classicLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" +
		"# yarn lockfile v1\n\n\nlodash@^4.17.21:\n  version \"4.17.21\"\n"
	berryLock = "# This file is generated by running \"yarn install\" inside your project.\n" +
		"# Manual changes might be lost - proceed with caution!\n\n" +
		"__metadata:\n  version: 8\n  cacheKey: 10c0\n\n" +
		"\"lodash@npm:^4.17.21\":\n  version: 4.17.21\n"
)

func writeFiles(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, body := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestInstallCommand(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		// wantRelease, when set, is the repo-relative vendored Yarn release
		// expected as the first argument (an absolute path at runtime).
		wantRelease string
		wantMgr     string
		wantArgs    []string
	}{
		// Non-yarn managers: unchanged by the Yarn resolution work.
		{
			name:     "pnpm",
			files:    map[string]string{"pnpm-lock.yaml": "x"},
			wantMgr:  "pnpm",
			wantArgs: []string{"install", "--frozen-lockfile", "--node-linker=hoisted"},
		},
		{
			name:     "npm ci via package-lock",
			files:    map[string]string{"package-lock.json": "x"},
			wantMgr:  "npm",
			wantArgs: []string{"ci"},
		},
		{
			name:     "npm ci via shrinkwrap",
			files:    map[string]string{"npm-shrinkwrap.json": "x"},
			wantMgr:  "npm",
			wantArgs: []string{"ci"},
		},
		{
			name:     "no lockfile → npm install without writing a lock",
			wantMgr:  "npm",
			wantArgs: []string{"install", "--no-package-lock"},
		},
		{
			name: "pnpm wins over yarn + npm",
			files: map[string]string{
				"pnpm-lock.yaml": "x", "yarn.lock": berryLock, "package-lock.json": "x",
			},
			wantMgr:  "pnpm",
			wantArgs: []string{"install", "--frozen-lockfile", "--node-linker=hoisted"},
		},
		{
			name:     "yarn wins over npm",
			files:    map[string]string{"yarn.lock": classicLock, "package-lock.json": "x"},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},

		// Classic: must stay exactly as it was — this is the dashboard shape.
		{
			name:     "classic lockfile, no packageManager → corepack's classic default",
			files:    map[string]string{"yarn.lock": classicLock, "package.json": "{}"},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},
		{
			name: "classic lockfile, packageManager pins yarn 1",
			files: map[string]string{
				"yarn.lock":    classicLock,
				"package.json": `{"packageManager":"yarn@1.22.22"}`,
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},
		{
			name:     "classic lockfile, no package.json at all",
			files:    map[string]string{"yarn.lock": classicLock},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},

		// Berry: the flag follows the version that will actually run.
		{
			name: "berry lockfile + packageManager pin → corepack shim, --immutable",
			files: map[string]string{
				"yarn.lock":    berryLock,
				"package.json": `{"packageManager":"yarn@4.1.0"}`,
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--immutable"},
		},
		{
			name: "packageManager pin carrying a corepack hash",
			files: map[string]string{
				"yarn.lock":    berryLock,
				"package.json": `{"packageManager":"yarn@3.6.4+sha224.deadbeef"}`,
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--immutable"},
		},
		{
			name: "classic lockfile + berry packageManager → berry runs, so --immutable",
			files: map[string]string{
				"yarn.lock":    classicLock,
				"package.json": `{"packageManager":"yarn@4.1.0"}`,
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--immutable"},
		},
		{
			name: "berry lockfile, nothing pinned → today's classic invocation (see warning)",
			files: map[string]string{
				"yarn.lock":    berryLock,
				"package.json": `{"name":"svc"}`,
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},

		// Vendored releases: run the repo's own file under node.
		{
			name: "yarnPath in .yarnrc.yml",
			files: map[string]string{
				"yarn.lock":                       berryLock,
				"package.json":                    "{}",
				".yarnrc.yml":                     "nodeLinker: node-modules\nyarnPath: .yarn/releases/yarn-4.1.0.cjs\n",
				".yarn/releases/yarn-4.1.0.cjs":   "// yarn 4\n",
				".yarn/releases/yarn-3.2.0.cjs":   "// yarn 3\n",
				".yarn/releases/yarn-3.2.0.cjs.x": "not a release\n",
			},
			wantRelease: ".yarn/releases/yarn-4.1.0.cjs",
			wantMgr:     "node",
			wantArgs:    []string{"install", "--immutable"},
		},
		{
			name: "quoted yarnPath",
			files: map[string]string{
				"yarn.lock":                     berryLock,
				".yarnrc.yml":                   "yarnPath: \"./.yarn/releases/yarn-4.1.0.cjs\"\n",
				".yarn/releases/yarn-4.1.0.cjs": "// yarn 4\n",
			},
			wantRelease: ".yarn/releases/yarn-4.1.0.cjs",
			wantMgr:     "node",
			wantArgs:    []string{"install", "--immutable"},
		},
		{
			name: "yarn-path in a classic .yarnrc redirecting at a berry release",
			files: map[string]string{
				"yarn.lock":                     berryLock,
				".yarnrc":                       "yarn-path \"./.yarn/releases/yarn-4.1.0.cjs\"\n",
				".yarn/releases/yarn-4.1.0.cjs": "// yarn 4\n",
			},
			wantRelease: ".yarn/releases/yarn-4.1.0.cjs",
			wantMgr:     "node",
			wantArgs:    []string{"install", "--immutable"},
		},
		{
			name: "release vendored without a yarnPath → newest of .yarn/releases",
			files: map[string]string{
				"yarn.lock":                     berryLock,
				".yarn/releases/yarn-3.6.4.cjs": "// yarn 3\n",
				".yarn/releases/yarn-4.1.0.cjs": "// yarn 4\n",
			},
			wantRelease: ".yarn/releases/yarn-4.1.0.cjs",
			wantMgr:     "node",
			wantArgs:    []string{"install", "--immutable"},
		},
		{
			name: "yarnPath naming a missing file falls back to the shim",
			files: map[string]string{
				"yarn.lock":    berryLock,
				"package.json": `{"packageManager":"yarn@4.1.0"}`,
				".yarnrc.yml":  "yarnPath: .yarn/releases/yarn-4.1.0.cjs\n",
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--immutable"},
		},
		{
			// The release sits outside .yarn/releases so the glob fallback
			// can't rescue the case: only the yarnPath parse is under test.
			name: "indented yarnPath is not a top-level key",
			files: map[string]string{
				"yarn.lock":            classicLock,
				".yarnrc.yml":          "npmScopes:\n  acme:\n    yarnPath: tools/yarn-4.1.0.cjs\n",
				"tools/yarn-4.1.0.cjs": "// yarn 4\n",
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},
		{
			// A vendored release is a Berry convention (Classic's `yarn
			// policies set-version` writes .js), so it selects --immutable
			// even against an unmigrated lockfile.
			name: "vendored release with a classic lockfile",
			files: map[string]string{
				"yarn.lock":                     classicLock,
				".yarn/releases/yarn-4.1.0.cjs": "// yarn 4\n",
			},
			wantRelease: ".yarn/releases/yarn-4.1.0.cjs",
			wantMgr:     "node",
			wantArgs:    []string{"install", "--immutable"},
		},

		// packageManager naming something other than yarn never selects Berry.
		{
			name: "packageManager names pnpm",
			files: map[string]string{
				"yarn.lock":    classicLock,
				"package.json": `{"packageManager":"pnpm@9.1.0"}`,
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},
		{
			name: "unparseable package.json",
			files: map[string]string{
				"yarn.lock":    classicLock,
				"package.json": "{ not json",
			},
			wantMgr:  "yarn",
			wantArgs: []string{"install", "--frozen-lockfile"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFiles(t, dir, tc.files)

			want := tc.wantArgs
			if tc.wantRelease != "" {
				want = append([]string{filepath.Join(dir, filepath.FromSlash(tc.wantRelease))}, want...)
			}
			mgr, args := installCommand(dir)
			if mgr != tc.wantMgr {
				t.Errorf("manager = %q, want %q", mgr, tc.wantMgr)
			}
			if !reflect.DeepEqual(args, want) {
				t.Errorf("args = %v, want %v", args, want)
			}
		})
	}
}

// TestYarnToolchainWarning pins the one shape the image cannot resolve: a
// Berry lockfile with no packageManager pin and no vendored release. The
// install still runs (and still fails) as it does today, so the warning is
// the only thing that tells an operator why.
func TestYarnToolchainWarning(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  bool
	}{
		{
			name:  "berry lockfile with nothing pinned",
			files: map[string]string{"yarn.lock": berryLock, "package.json": `{"name":"svc"}`},
			want:  true,
		},
		{
			name:  "berry lockfile, no package.json",
			files: map[string]string{"yarn.lock": berryLock},
			want:  true,
		},
		{
			name: "berry lockfile with a packageManager pin",
			files: map[string]string{
				"yarn.lock":    berryLock,
				"package.json": `{"packageManager":"yarn@4.1.0"}`,
			},
		},
		{
			name: "berry lockfile with a vendored release",
			files: map[string]string{
				"yarn.lock":                     berryLock,
				".yarn/releases/yarn-4.1.0.cjs": "// yarn 4\n",
			},
		},
		{
			name:  "classic lockfile",
			files: map[string]string{"yarn.lock": classicLock, "package.json": "{}"},
		},
		{
			name: "yarn.lock absent",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFiles(t, dir, tc.files)
			got := yarnToolchainWarning(dir)
			if (got != "") != tc.want {
				t.Errorf("yarnToolchainWarning() = %q, want warning: %v", got, tc.want)
			}
		})
	}
}

func TestDeclaredYarnMajor(t *testing.T) {
	cases := []struct {
		packageJSON string
		want        int
	}{
		{`{"packageManager":"yarn@4.1.0"}`, 4},
		{`{"packageManager":"yarn@2.4.3"}`, 2},
		{`{"packageManager":"yarn@1.22.22"}`, 1},
		{`{"packageManager":" yarn@10.0.0 "}`, 10},
		{`{"packageManager":"yarn@4.1.0+sha224.abc"}`, 4},
		{`{"packageManager":"pnpm@9.1.0"}`, 0},
		{`{"packageManager":"yarn@stable"}`, 0},
		{`{"packageManager":"yarn"}`, 0},
		{`{"name":"svc"}`, 0},
		{`{ not json`, 0},
	}
	for _, tc := range cases {
		t.Run(tc.packageJSON, func(t *testing.T) {
			dir := t.TempDir()
			writeFiles(t, dir, map[string]string{"package.json": tc.packageJSON})
			if got := declaredYarnMajor(dir); got != tc.want {
				t.Errorf("declaredYarnMajor() = %d, want %d", got, tc.want)
			}
		})
	}
}

// TestYarnLockIsBerry checks the lockfile sniff on its own, including a
// lockfile long enough that the marker is only reachable within the bounded
// read (a real Berry lockfile is megabytes; only its head is scanned).
func TestYarnLockIsBerry(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{"berry", berryLock, true},
		{"classic", classicLock, false},
		{"empty", "", false},
		{"berry with a long entry after the marker", berryLock + strings.Repeat("# padding\n", 4096), true},
		{"__metadata only as an indented value", "deps:\n  __metadata: 8\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFiles(t, dir, map[string]string{"yarn.lock": tc.content})
			if got := yarnLockIsBerry(dir); got != tc.want {
				t.Errorf("yarnLockIsBerry() = %v, want %v", got, tc.want)
			}
		})
	}

	t.Run("no yarn.lock", func(t *testing.T) {
		if yarnLockIsBerry(t.TempDir()) {
			t.Error("yarnLockIsBerry() = true with no lockfile, want false")
		}
	})
}

func TestMetadata(t *testing.T) {
	d := &detector{}
	if d.Name() != "node" {
		t.Errorf("Name() = %q, want \"node\"", d.Name())
	}
	if err := d.EnsureToolchain(context.Background()); err != nil {
		t.Errorf("EnsureToolchain() = %v, want nil (Node is baseline)", err)
	}
	if len(d.AllowedHosts()) == 0 {
		t.Error("AllowedHosts() should be non-empty")
	}
	if len(d.VerifyHosts()) == 0 {
		t.Error("VerifyHosts() should be non-empty")
	}
	if err := d.Finalize("/work", nil); err != nil {
		t.Errorf("Finalize() = %v, want nil", err)
	}
}

// TestEnvRedirectsToSharedCache verifies that when cacheDir is set, each
// supported package manager's cache env var points into a subdirectory
// of the shared cache — moving big tarball downloads off the
// memory-backed /home/agent tmpfs.
func TestEnvRedirectsToSharedCache(t *testing.T) {
	d := &detector{}
	got := d.Env("/cache", nil)
	want := []string{
		"YARN_CACHE_FOLDER=/cache/yarn",
		"YARN_GLOBAL_FOLDER=/cache/yarn-berry",
		"npm_config_cache=/cache/npm",
		"npm_config_store_dir=/cache/pnpm",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Env(\"/cache\", nil) = %v, want %v", got, want)
	}
}

// TestEnvEmptyCacheDirIsNoop confirms that with no shared cache mounted
// the detector falls back to each package manager's default location.
// Important so standalone agentbox runs (no /cache volume) keep working.
func TestEnvEmptyCacheDirIsNoop(t *testing.T) {
	d := &detector{}
	if got := d.Env("", nil); got != nil {
		t.Errorf("Env(\"\", nil) = %v, want nil (let pkg managers use defaults)", got)
	}
}
